# -*- coding: utf-8 -*-
"""topoplot_mne.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YhQVfjLv8tFa9ArIkX04GskkPTFt3oal
"""

!pip install mne
import mne
from matplotlib.pyplot import figure
import matplotlib.pyplot as plt
import matplotlib.text
#https://mne.tools/1.1/generated/mne.viz.plot_topomap.html
import numpy as np
from google.colab import drive
import pandas as pd
import pickle
from matplotlib.pyplot import figure
drive.mount('/content/drive')
path = '/content/drive/MyDrive/Doctorado/Cocuco/mejor_canal/'

#builtin_montages = mne.channels.get_builtin_montages(descriptions=True)
#for montage_name, montage_description in builtin_montages:
#    print(f'{montage_name}: {montage_description}')

montage = mne.channels.make_standard_montage('brainproducts-RNP-BA-128', head_size='auto')

combinaciones = [(i,j) for i in range(199) for j in range(i+1,200)]

canales = ['Fp1', 'Fz', 'F3', 'F7', 'FT9', 'FC5', 'FC1', 'C3', 'T7', 'TP9', 'CP5',
           'CP1', 'Pz', 'P3', 'P7', 'O1', 'Oz', 'O2', 'P4', 'P8', 'TP10', 'CP6',
           'CP2', 'C4', 'T8', 'FT10', 'FC6', 'FC2', 'F4', 'F8', 'Fp2', 'AF7',
           'AF3', 'AFz', 'F1', 'F5', 'FT7', 'FC3', 'C1', 'C5', 'TP7', 'CP3', 'P1', 
           'P5', 'PO7', 'PO3', 'POz', 'PO4', 'PO8', 'P6', 'P2', 'CPz', 'CP4', 
           'TP8', 'C6', 'C2', 'FC4', 'FT8', 'F6', 'AF8', 'AF4', 'F2', 'FCz', 'Cz']

bandas = [(0.5,4), (4,8), (8,12.5), (12.5,30), (30,50), (50,70), (70,100)]
sujetos = set(range(2,51))
sujetos -= {6}

pos = np.zeros((64,2))
channames = []
n=0
for ch in montage.get_positions()['ch_pos']:
    if ch in canales:  
        coords = montage.get_positions()['ch_pos'][ch]
        channames.append(ch)
        pos[n,0] = coords[0]
        pos[n,1] = coords[1]
        n=n+1

total = pd.DataFrame()
with open(path + 'dic_cohen_canales.pkl', 'rb') as f:
    dic_cohen_canal= pickle.load(f)    
for s in sujetos:
    df = pd.DataFrame(dic_cohen_canal[s])
    total = total.add(df, fill_value=0)
total.divide(len(sujetos))

fig, ((ax1, ax2, ax3), (ax4, ax5, ax6), (ax7, ax8, ax9)) = plt.subplots(nrows=3, ncols=3, figsize=(20, 10))
l = [ax1,ax2,ax3,ax4,ax5,ax6,ax7,ax8,ax9]

for j,i in enumerate(range(30,120,10)):
    vals = np.array(total[channames].iloc[i])
    tiempo = str(i*4) + ' ms'
    im,cm   = mne.viz.plot_topomap(vals,pos, axes=l[j], show=False, cmap='viridis', size=8, vlim=(15, 17), sensors='b+')  #names=canales
    l[j].set_title(tiempo, fontsize=16)

# manually fiddle the position of colorbar
ax_x_start = 0
ax_x_width = 1
ax_y_start = -0.1
ax_y_height = 0.1
cbar_ax = fig.add_axes([ax_x_start, ax_y_start, ax_x_width, ax_y_height])
clb = fig.colorbar(im, cax=cbar_ax, orientation='horizontal')
clb.ax.set_title("Cohen's D",fontsize=18) # title on top of colorbar
figure(figsize=(18, 6), dpi=80)
plt.show()

